name: bilibili
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.2
  get: 4.1.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

